config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  

  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :orders, only: [:index, :show, :new, :create]
  resources :order_items, only: [:create, :update, :destroy]

  root "products#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    %w[id email created_at updated_at]
  end       
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  def self.ransackable_attributes(auth_object = nil)
    %w[id name created_at updated_at]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  accepts_nested_attributes_for :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "order_id", "price", "product_id", "quantity", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items

  has_one_attached :image


  validates :name, :price, :stock, presence: true

  def self.ransackable_associations(auth_object = nil)
    %w[category order_items orders]
  end
  
  def self.ransackable_attributes(auth_object = nil)
    %w[id name price stock created_at updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to products_path # or wherever
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order_item = OrderItem.new(order_item_params)
    if @order_item.save
      redirect_to @order_item.order, notice: 'Item added to order.'
    else
      render :new
    end
  end

  def update
    @order_item = OrderItem.find(params[:id])
    if @order_item.update(order_item_params)
      redirect_to @order_item.order, notice: 'Order item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy
    redirect_to @order_item.order, notice: 'Order item was successfully removed.'
  end

  private

  def order_item_params
    params.require(:order_item).permit(:order_id, :product_id, :quantity, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    # @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.build(order_params)
    if @order.save
      OrderMailer.with(order: @order).order_confirmation.deliver_later
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(:total_price, order_items_attributes: [:product_id, :quantity, :price])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Work in progress</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">E-Commerce</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', categories_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to orders_path, class: "nav-link" do %>
               <i class="fas fa-shopping-cart text-white"></i>Cart
              <span class="badge bg-primary"><%= 1 %></span>
            <% end %>
            </li>
          <li class="nav-item">
            <%= link_to 'My Orders', orders_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SellProduct</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container mt-4">

      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Work in progress</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/index.html.erb
<h1>Products</h1>

<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <% if product.image.attached? %>
          <%= image_tag product.image, class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= product.name %></h5>
          <p class="card-text"><%= truncate(product.description, length: 100) %></p>
          <p class="card-text"><strong>Price: </strong><%= number_to_currency(product.price) %></p>
          <p class="card-text"><strong>Stock: </strong><%= product.stock %></p>
          <a href="<%= product_path(product) %>" class="btn btn-primary text-white">View Product</a>
          <a href="<%= "#" %>" class="btn btn-secondary text-white">Add to Cart</a>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>